
title: Lab 1 GEOS270 2021W1
# remote_theme: June-Skeeter/rc-workshop-template
remote_theme: pmarsceill/just-the-docs
search_enabled: false
github_repo_url: "https://github.com/June-Skeeter/History-of-Mapping-Spatial-Analysis-GIS"

# license information for workshop content
license_name: "Creative Commons Attribution 4.0 International License"
license_url: "http://creativecommons.org/licenses/by/4.0/"
license_image_url: "https://i.creativecommons.org/l/by/4.0/88x31.png"

# required for building jekyll site locally
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

